set(CMAKE_SYSTEM_NAME Windows)

if(NOT DEFINED CMAKE_C_COMPILER)
  set(CMAKE_C_COMPILER cl CACHE STRING "" FORCE)
endif()

if(NOT DEFINED CMAKE_CXX_COMPILER)
  set(CMAKE_CXX_COMPILER cl CACHE STRING "" FORCE)
endif()
